In [1]:
import numpy as np

np.array([1,2,3])

x = np.array([1,2,3])
u = np.array([[1,2,3]])

print(x)
print(x.shape)
print()
print(u)
print(u.shape)

[1 2 3]
(3,)

[[1 2 3]]
(1, 3)


In [5]:
v = np.array([[1],[2],[3]])
print(v)
print(v.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [6]:
# linalg (linear algebra)
!pip install scipy

In [2]:
from scipy import linalg
import numpy as np

s = np.array([2,3,1])

# 단위 벡터 (u) >> s / ||s||

print(linalg.norm(s)) # ||s||
# print(s / linalg.norm(s))
norm = s / linalg.norm(s)
print(norm)


3.7416573867739413
[0.53452248 0.80178373 0.26726124]


In [3]:
np.array([1, -3])

x = np.array([1, -3])

# u = x / ||x||
u = x / linalg.norm(x)
u

array([ 0.31622777, -0.9486833 ])

In [4]:
np.array([-6, -8])

x = np.array([-6, -8])

# u = x / ||x||
u = x / linalg.norm(x)
u

array([-0.6, -0.8])

In [5]:
import numpy as np

np.zeros(5) # 0벡터 5개 생성

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros(5).shape

(5,)

In [7]:
s = (2, 2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

선형결합과 생성(span)

In [9]:
import numpy as np

a = np.array([2,4])
b = np.array([1,6])

print(a)
print()
print(b)

[2 4]

[1 6]


In [10]:
c = (4*a) + ((-3)*b)
print(c)
# 넘파이 배열로 변환 >> 원소에 접근 가능
# >> 원소 간 연산이 가능

[ 5 -2]


벡터 공간, 부분공간 기저

In [13]:
import numpy as np

np.array([[2,7],[5,1]])


array([[2, 7],
       [5, 1]])

In [14]:
# rank
m = np.array([[2,7],[5,1]])
np.linalg.matrix_rank(m)
# rank 몇 개? >> 2개

2

In [15]:
np.array([[2,4],[3,6]])

array([[2, 4],
       [3, 6]])

In [16]:
m_1 = np.array([[2,4],[3,6]])
np.linalg.matrix_rank(m_1)
# rank >> 1개
# why? >> 벡터 간 관계가 선형종속

1

벡터의 내적과 외적

In [17]:
# 벡터의 덧셈과 뺄셈

x = [2,3]
y = [3,1]

z = [i+j for i,j in zip(x,y)]

print(z)

[5, 4]


In [19]:
list(zip(x,y))

[(2, 3), (3, 1)]

In [20]:
i,j = list(zip(x,y))

print(i)
print(j)

(2, 3)
(3, 1)


In [22]:
# zip (*iterable)

zip([1,2,3], [4,5,6])

In [23]:
list(zip([1,2,3], [4,5,6]))

[(1, 4), (2, 5), (3, 6)]

In [24]:
u = np.array(x)
v = np.array(y)

print(u)
print(v)

[2 3]
[3 1]


In [25]:
w = u+v
print(w)

[5 4]


In [27]:
x = [2,3]
y = [3,1]

z = [i-j for i,j in zip(x,y)]
print(z)

[-1, 2]


In [28]:
list(zip(x,y))

[(2, 3), (3, 1)]

In [30]:
# 벡터의 곱셈

x = [3,4]
c = 8 # scala

# 원소간 곱하는 방법: 리스트 내포(list comprehension)
z = [c*i for i in x]

print(z)

[24, 32]


In [32]:
# 원소간 곱하는 방법: 넘파이 배열로 변환
u = np.array([3,4])

In [33]:
w = u*c
print(w)

[24 32]


In [35]:
# 벡터의 내적⭐️⭐️⭐️

import numpy as np

u = np.array([6,6])
v = np.array([12,0])

uv = np.dot(u, v)
print(uv)

72


In [39]:
# 정사영 (projection)⭐️⭐️⭐️

import numpy as np

print(np.arange(1*2*3))
print()
np.arange(1*2*3).reshape((1,2,3))
# >> 3차원에, 2행 3열(2x3)

[0 1 2 3 4 5]



array([[[0, 1, 2],
        [3, 4, 5]]])

In [44]:
a = np.arange(1*2*3).reshape((1,2,3))
b = np.arange(1*2*3).reshape((1,2,3))
c = np.arange(1*2*3).reshape((1,3,2))
d = np.arange(1*2*3).reshape((2,1,3))
e = np.arange(1*2*3).reshape((2,3,1))
f = np.arange(1*2*3).reshape((3,1,2))
j = np.arange(1*2*3).reshape((3,2,1))

print(a)
print(b)
print()

# print(np.dot(a,b))
# ValueError: shapes (1,2,3) and (1,2,3) not aligned: 3 (dim 2) != 2 (dim 1)

print(np.dot(b,c))


[[[0 1 2]
  [3 4 5]]]
[[[0 1 2]
  [3 4 5]]]

[[[[10 13]]

  [[28 40]]]]


In [46]:
import numpy as np

u = np.array([3, -6])
v = np.array([-7, 9])

print(u)
print(v)

[ 3 -6]
[-7  9]


In [47]:
np.dot(u, v)

-75

In [48]:
u = np.array([-3, 4, 7])
v = np.array([-4, -9, 5])

uv = np.dot(u, v)
print(uv)

11


In [49]:
# 외적

a = (1, 3, 5)
b = (2, 4, 6)

In [50]:
# 외적 함수

def cross(a, b):
    c = [a[1]*b[2] - a[2]*b[1],
         a[2]*b[0] - a[0]*b[2],
         a[0]*b[1] - a[1]*b[0]]
    
    return c
    

In [52]:
cross(a,b)
# x: -2, y: 4, z: -2

[-2, 4, -2]

In [54]:
# numpy 이용한 벡터 외적 계산
np.cross(a,b)

array([-2,  4, -2])

In [55]:
import numpy as np

a = np.array([5, -13, 8])
b = np.array([-2, 11, -14])

print(np.cross(a,b))

[94 54 29]


In [56]:
# 직교 벡터

import numpy as np

# 크기가 (1,2) 2차원 배열(행렬)
a = np.array([1,2])
print(a)

[1 2]


In [57]:
np.linalg.norm(a) # default: L2 norm

2.23606797749979

In [59]:
np.linalg.norm(a, ord=2) # L2 norm(default)

2.23606797749979

In [60]:
np.linalg.norm(a, ord=1) # L1 norm

3.0

In [62]:
import numpy as np

a = np.array([-2, 12])
print(a)
print()
print(np.linalg.norm(a))

[-2 12]

12.165525060596439


In [64]:
np.array([5**0.5, 12])

array([ 2.23606798, 12.        ])

In [63]:
a = np.array([5**0.5, 12])
np.linalg.norm(a)

12.206555615733702

직교벡터_유사도 기반 거리

In [2]:
# 1. 유클리디언 거리

from scipy.spatial import distance

# 두 점 p1, p2 명시
p1 = (1,2,3)
p2 = (4,5,6)

# p1과 p2 사이의 유클리드 거리를 계산합니다.
d = distance.euclidean(p1, p2)
print("Euclidean distance: ", d)


Euclidean distance:  5.196152422706632
